spring:
  profiles:
    active: peer1
server:
  port: 8761

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:root@peer1:8761/eureka/,http://root:root@peer2:8769/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

security:
  basic:
    enabled: true
  user:
    name: root
    password: root


