eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true

#熔断器超时配置，与zuul配置时并发量达到一定程度hystrix会失效
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000