eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/

server:
  port: 8766

spring:
  application:
    name: service-zuul

zuul:
  routes:
      api-a:
        path: /api-a/**
        serviceId: SERVICE-RIBBON
      api-b:
        path: /api-b/**
        serviceId: SERVICE-FEIGN
