eureka:
  client:
    serviceUrl:
     # defaultZone: http://root:root@localhost:8761/eureka/
     defaultZone: http://root:root@peer1:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-eureka


